### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by iaemonbd** [Expert-Hacker/E-TOOL#1]
Not working for ngrok

**Comment by Expert-Hacker** [comment]
As i checked today, its working well!
please find bellow screenshot 👍 
![E_Tool](https://user-images.githubusercontent.com/63892972/125194747-364a8500-e270-11eb-93dd-d3813f79ad10.jpeg)

**Comment by Monurajpp** [comment]
Direct link not generated 
![Uploading Screenshot_2023-08-12-20-18-00-91.jpg…]()
