### ISSUE TITLE
script can't see ngrok

### ISSUE THREAD

**Issue by xFm512** [Expert-Hacker/E-TOOL#2]
the script says that you need to install ngrok although it is installed and working.
![Screenshot_20220502-030620](https://user-images.githubusercontent.com/104738988/166166420-f1bcbacd-d21a-43ea-9e41-0979168788bb.png)
![Screenshot_20220502-030626](https://user-images.githubusercontent.com/104738988/166166421-666d764d-ab27-410f-bf9e-5c88db57b1fd.png)

**Comment by 000ph** [comment]
same issue

**Comment by Expert-Hacker** [comment]
ngrok should be available in home.

to check: 
Type **cd**
Type **ls**
if you can't see ngrok, then it's installed somewhere.
